### ISSUE TITLE
Fix Naviagation Menu generation

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/docker-infradocs#3]
Currently the navigation menu is generated based on a file name search of the indir in the docker container. This creates a basic JSON structure using the name format of the files which is used to generate the navigation menu. 

Ideally it would be much easier if a navigation menu could be generated based on the pages available under the blueprints/ folder rather than creating a new file/process to do this.

**Comment by webilhan** [comment]
@roleyfoley With jekyll it is not possible to generate hierarchical menu from folder structure. We can use jekyll collections with Front Matter:
So file at: `/blueprints/msw/automation/alm/alm/index.html` should have following start
```
---
title: Deployment
layout: diagram
product: automation
environment: alm
segment: alm
---
```
In that case we can make `blueprints` as collection and generate hierarchical menu dynamically.

**Comment by roleyfoley** [comment]
Thanks @webilhan. We currently generate each of the html files so that would be easy to add to the process. Happy to go with that suggestion

**Comment by webilhan** [comment]
@roleyfoley Updated menu generation. Now it will generate depending on files in `_blueprints` folder with front matter as discussed above. Also added highlight current menu item in navigation.

**Comment by roleyfoley** [comment]
Happy with the changes, thanks
