### ISSUE TITLE
Navigation Menu formatting and layout improvements

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/docker-infradocs#4]
The navigation menu at the moment is not very intuitive and doesn't easily identify as a navigation selection menu.

Not entirely sure how the menu could be better represented. 

The intention of the menu is to get you to a specific deployment. 

To do:
Provide an alternative display of the the deployment finder menu on the left of the page

**Comment by ml019** [comment]
NOT very intuitive....? @roleyfoley

**Comment by webilhan** [comment]
@roleyfoley Updated menu with "tree" style. Pushed to master, please check.

**Comment by roleyfoley** [comment]
Looks great much easier to follow. With the class based navigation in #3 will this group the folders based on their names?

**Comment by roleyfoley** [comment]
Happy with the changes, thanks
