### ISSUE TITLE
Mouse over on resources to show resource properties 

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/docker-infradocs#5]
Currently to show the properties of a resource you need to click on them and the card window expands to show the properties. Instead it would be nice if a hover box shows up when you mouse over the resource properties and shows these details. 

If the hover box is clicked then the box should stay visible until another resource is selected or the resource page is closed. 

Page : /blueprints/msw/automation/alm/alm/index.html

**Before Click** 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/16523764/38853091-86775f08-425f-11e8-874c-7d4ae0d751ef.png">

**After Click**
<img width="266" alt="image" src="https://user-images.githubusercontent.com/16523764/38853101-8cad1d36-425f-11e8-8ac9-a5212e86829e.png">

**Comment by webilhan** [comment]
@roleyfoley Pushed changes to master. Please check.

**Comment by roleyfoley** [comment]
Thanks @webilhan 
Happy to close this one off
